### ISSUE TITLE
button hover colour

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/artwork-maia-gtk#1]
Seems we might have still missed some ...
![gtk-maia-hover-button](https://cloud.githubusercontent.com/assets/5050022/11968444/a0c2aa78-a90c-11e5-9b53-d075cad01b54.png)

**Comment by Kirek** [comment]
gtk2 or gtk3 application? it's thus?

**Comment by philmmanjaro** [comment]
This is **thus**, correct.

**Comment by philmmanjaro** [comment]
I didn't test yet GTK2 apps ...
```
[2015-12-22 22:55:59] [thus] INFO: Using GTK v3.18.6
[2015-12-22 22:55:59] [updater] INFO: Thus Internet version: 0.9.1
```
