### ISSUE TITLE
Seems we need to adopt to GTK 3.20

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/artwork-maia-gtk#2]
To my current knowledge even **breeze-gtk** not yet supports **GTK 3.20**. So it seems we have to wait for a fix. Using **adwaita** for now is a workaround for now ...

**Comment by philmmanjaro** [comment]
Unfortunately, a GTK 3.20 version of theme doesn't exist in any form yet. Technically speaking, the 3.18 version wasn't even feature complete. Instead of fixing its remaining problems, it may be more prudent to restructure and polish the theme as it is rewritten for GTK 3.20 and up, effectively abandoning 3.18 development. 

That shouldn't be a problem since, in theory, this would be the last time we are required to rewrite the CSS. So yes, GTK 3 applications will be shocking and ugly for a time, but the theme should remain stable for a long while after the rewrite is complete. That is, until GTK 4: https://bugs.kde.org/show_bug.cgi?id=361066

**Comment by philmmanjaro** [comment]
Seems they have ported it now. See also [here](https://git.archlinux.org/svntogit/packages.git/tree/trunk?h=packages/breeze-gtk).

**Comment by Kirek** [comment]
https://github.com/manjaro/artwork-maia-gtk/commit/6fd2b8c3d4f84b3e134f3d06b39c027dbf423d5a
https://github.com/manjaro/packages-community/commit/4e0d7338f4d71fcc278f082980f0b6dc6ec34608

**Comment by philmmanjaro** [comment]
Do we still need the **gtk 3.20 branch**?

**Comment by Kirek** [comment]
No, can be deleted
